version: "3.0"
networks:
  internalnetwork:
services:
  db:
    image: ilyaavdeev/pg-words:1.1
    container_name: postgres_container
    environment:
      PGDATA: /var/lib/postgresql/data
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5432:5432
    networks:
      - internalnetwork
  ojegov-uploader:
    image: ilya.avdeev/ojegov-builder:1.0
    container_name: smart-ojegov
    build:
      args:
        WORKDIR_NAME_ARG: "/usr/src/app"
        OUTPUTDIR_NAME_ARG: "/output"
      context: .
      dockerfile: ./Ojegov-vocabulary/Dockerfile
    volumes:
      - ./output:/output
    networks:
      - internalnetwork