quarkus:
  hibernate-orm:
    database:
      generation: validate
    log:
      sql: true
  datasource:
    db-kind: postgresql
    username: p_user
    password: p_password
    jdbc:
      url: jdbc:postgresql://localhost:5432/words
  openapi:
    generator:
      spec: word-games.yaml
      base-package: avdeev.one
      reactive: false
